[processor/sllogformat] skip with warning for empty log lines
ScienceLogic/otel-components pull request #242
Opened 2024-08-09 01:59 UTC by jakobreinwald

These changes allow for the processor to gracefully skip log lines that contain no printable characters instead of throwing an error. By returning a different type of error when the message body is empty and no profiles are matched, we can return a warning when processing the empty log line instead of throwing an error with a stack trace and record dump. This change will make it clear to users of the collector that there is not actually an error, but that the log line was empty.

2024-08-21 20:40 UTC, b3arpsl requested changes

2024-08-21 20:40 UTC, b3arpsl commented on Makefile
> -all: install-tools gotidy gofmt gogovulncheck gotest
Why did this get removed

2024-08-21 20:40 UTC, b3arpsl commented on sllogformatprocessor/batch_logs.go
> +func AsStringWithoutUnprintables(v pcommon.Value) string {
Please add unit testing around this functionaility

2024-08-21 20:40 UTC, b3arpsl commented on sllogformatprocessor/batch_logs.go
> +				if err != nil && errors.Is(err, skipLine) {
Please add some unit testing around this logic to ensure it is working

2024-08-22 19:19 UTC, shanemalachow-SL requested changes

2024-09-17 16:17 UTC, shanemalachow-SL reviewed
This is looking good now! From a functional perspective, I think this is fine. The code coverage for unit tests is a little lacking. We should ideally test the error paths as well, like https://github.com/ScienceLogic/otel-components/pull/242/files/a4a3612c68f1755b24b74bc1277fd948b0ff2f9c..e1f81913bcf6971535c0820a9341fa3207a8dcf7#diff-f9f640c1a548440250208d7c90a781f27a34d1e2422977452691de378ab141c2R408 

Also from a nit standpoint, the tests should probably go into a `match_profile_test.go` file and not in `config_test.go`.

That should be enough to make this work.

2025-10-21 07:29 UTC, closed without merging